version: "3.9"

services:
  db:
    build:
      context: ./mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      DB_ROOT_PW: 123abc
      DB_NAME: wordpress
      DB_USER: margam2
      DB_PASSWORD: abc
      
  wordpress:
    depends_on:
      - db
    build: 
      context: ./wordpress
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    ports:
      - "8000:80"
      
volumes:
  db_data: {}
  wordpress_data: {}