FROM debian:jessie

RUN apt update
RUN apt upgrade
RUN apt install -y wget

#install LAMP
RUN apt-get install -y apache2
RUN apt-get update
RUN apt-get install -y php5 libapache2-mod-php5 php5-mcrypt php5-mysql unzip

#install Wordpress
RUN cd /var/www/html/ && \
    wget https://wordpress.org/latest.zip && \
    apt install -y unzip && \
    unzip -q latest.zip && \
    chown -R www-data:www-data /var/www/html/wordpress && \
    chmod -R 755 /var/www/html/wordpress && \
    mkdir -p /var/www/html/wordpress/wp-content/uploads && \
    chown -R www-data:www-data /var/www/html/wordpress/wp-content/uploads


EXPOSE 80

VOLUME /var/www/html

CMD apachectl -D FOREGROUND