FROM debian:jessie

ENV DB_ROOT_PW=123abc
ENV DB_NAME=lab3
ENV DB_USER=margam
ENV DB_PASSWORD=123abc

RUN apt-get update
RUN apt-get upgrade
RUN apt install -y wget
RUN wget http://repo.mysql.com/mysql-apt-config_0.8.9-1_all.deb
RUN apt install -y lsb-release
RUN dpkg -i mysql-apt-config_0.8.9-1_all.deb
RUN apt update 
RUN echo "mysql-server mysql-server/root_password password $DB_ROOT_PW" | debconf-set-selections
RUN echo "mysql-server mysql-server/root_password_again password $DB_ROOT_PW" | debconf-set-selections
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server
RUN sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/my.cnf

VOLUME [ "/var/lib/mysql" ]

EXPOSE 3306

CMD service mysql restart && \
    mysql --user=root --password=$DB_ROOT_PW -e "CREATE USER '$DB_USER'@'%' IDENTIFIED BY '$DB_PASSWORD';" || true && \
    mysql --user=root --password=$DB_ROOT_PW -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;" && \
    mysql --user=root --password=$DB_ROOT_PW -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO $DB_USER IDENTIFIED BY '$DB_PASSWORD';" && \
    mysqld

